# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/np-dev-hello-world',
                'doc_host': 'https://niloy71.github.io',
                'git_url': 'https://github.com/niloy71/np-dev-hello-world',
                'lib_path': 'np_dev_hello_world'},
  'syms': { 'np_dev_hello_world.core': { 'np_dev_hello_world.core.foo': ('test.html#foo', 'np_dev_hello_world/core.py'),
                                         'np_dev_hello_world.core.say_hello': ('test.html#say_hello', 'np_dev_hello_world/core.py')}}}
