# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/test.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/test.ipynb 0
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/test.ipynb 2
def foo(): pass

# %% ../nbs/test.ipynb 4
say_hello("Isaac")
