name: Run My Python Script

permissions:
  contents: write
  pages: write

on:
  # schedule:
  #   - cron: '0 0/3 * * *'
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - run: python -m pip install jupyter
      - run: jupyter nbconvert --to notebook --execute nbs/test.ipynb