name: Run My Python Script

permissions:
  contents: write
  pages: write

on:
  # schedule:
  #   - cron: '0 0/3 * * *'
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run My Script
        run: python ./nbs/00_core.ipynb
        working-directory: ${{ github.workspace }}