name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  # schedule:
  #   - cron: '0 0/3 * * *'
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install required packages
        run: |
          pip install pandas

      - uses: fastai/workflows/quarto-ghp@master