name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  # schedule:
  #   - cron: '0 0/3 * * *'
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
      # - name: Install required packages
      #   run: |
      #     pip install pandas
      # - name: Check installed packages
      #   run: |
      #     python -c "import pandas; print(pandas.__version__)"
      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.version }}
          cache: "pip"
          cache-dependency-path: settings.ini
      - name: Install Dependencies
        env:
          USE_PRE: ${{ inputs.pre }}
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          if [ $USE_PRE ]; then
            pip install -Uq git+https://github.com/fastai/ghapi.git
            pip install -Uq git+https://github.com/fastai/fastcore.git
            pip install -Uq git+https://github.com/fastai/execnb.git
            pip install -Uq git+https://github.com/fastai/nbdev.git
            wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
            sudo dpkg -i quarto*.deb
          else
            pip install -Uq nbdev
          fi
          test -f setup.py && pip install -e ".[dev]"
          nbdev_docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: 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
          force_orphan: true
          publish_dir: ./_docs
          # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
          # You can swap them out with your own user credentials.
          user_name: niloy71
          user_email: niloyrashid71@gmail.com
