name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  # schedule:
  #   - cron: '0 0/3 * * *'
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
      - name: Check Python version
        run: |
          python --version
      - name: Activate Python environment
        run: |
          source ${{ env.PYENV_ROOT }}/versions/3.10.6/bin/activate
      - name: Install required packages
        run: |
          pip install pandas
      - name: Check installed packages
        run: |
          python -c "import pandas; print(pandas.__version__)"
      - name: 'build-docs'
        description: 'Create docs with nbdev'
        inputs:
          pre:
            description: 'Install prerelease nbdev/execnb from master?'
            required: false
            default: ''
          version:
            description: 'Version of python to set up'
            required: false
            default: '3.9'
          ghtoken:
            description: 'GitHub token'
            default: ${{ github.token }}
            required: false

        runs:
          using: "composite"
          steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: ${{ inputs.version }}
                cache: "pip"
                cache-dependency-path: settings.ini
            - name: Install Dependencies
              env:
                USE_PRE: ${{ inputs.pre }}
              shell: bash
              run: |
                set -ux
                python -m pip install --upgrade pip
